services:
  yukiapi:
    image: yukiapi
    build:
      context: .
      dockerfile: YukiAPI/Dockerfile

  infrastructure:
    image: infrastructure
    build:
      context: .
      dockerfile: Infrastructure/Dockerfile

  core:
    image: core
    build:
      context: .
      dockerfile: Core/Dockerfile

  yukiapi.tests:
    image: yukiapi.tests
    build:
      context: .
      dockerfile: YukiAPI.Tests/Dockerfile
